### ISSUE TITLE
[ERROR] Incorrect model run in python client 

### ISSUE THREAD

**Issue by ancs21** [RedisAI/redisai-examples#10]
Hello,
I run example, it errors.
https://github.com/RedisAI/redisai-examples/blob/baed19ba6fbcd939ea9f3a5a1fda8fe73f1011d3/python_client/sklearn_boston_house_price_prediction.py#L21

**Comment by hhsecond** [comment]
HI @ancs21, That's because of a recent change in redisai python client I suppose. We'll fix the example repo soon but in between if you wanna try it, use `inputs` and `outputs` instead of `input` and `output`

**Comment by ancs21** [comment]
@hhsecond Thanks. Please fix soon.
